name: 'Check Commitlint'
description: 'Ensure that at least one PR commit satisfies commitlint'
inputs:
  github_token:
    description: 'Token used to access GitHub API'
    required: true
  types:
    description: 'Comma-separated list of commit types accepted'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
