name: 'Check PR Commits'
description: 'Ensure that at least one PR commit satisfies conventional commits'
inputs:
  github_token:
    description: 'Token used to access GitHub API'
    required: true
  commitlint_config_path:
    description: 'Path to commitlint config'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
